export interface Project {
  id: number;
  slug: string;
  title: string;
  formalTitle: string;
  category: string;
  filterType: string;
  subtitle: string;
  image: string;
  gallery: string[];
  location: string;
  year: string;
  area: string;
  scopeOfWork: string;
  overview: string;
  designTypes: string[];
}

export const projects: Project[] = [
  {
    id: 1,
    slug: "mr-jagan-residence",
    title: "Mr. Jagan Residence",
    formalTitle: "KRISHNA AISHWARYAM",
    category: "Residential Architecture",
    filterType: "Residential",
    subtitle: "A contemporary tropical courtyard residence.",
    image: "/images/interiors/jagan_int.png",
    gallery: [
      "/images/jagan/1.jpg",
      "/images/jagan/6.jpg",
      "/images/jagan/65.jpg",
      "/images/jagan/67.jpg",
      "/images/jagan/74.jpg",
    ],
    location: "COIMBATORE",
    year: "2023",
    area: "9,565 SQFT",
    scopeOfWork: "ARCHITECTURE, INTERIOR, STRUCTURAL DESIGN, LANDSCAPE",
    overview: "A contemporary take on a traditional courtyard house design, Krishna Aishwaryam integrates modern tropical aesthetics with functional living spaces. The design emphasizes natural ventilation and light, creating a seamless connection between indoor and outdoor environments through strategically placed courtyards and large openings.",
    designTypes: ["Architectural", "Structural", "Interior", "Landscape"],
  },
  {
    id: 2,
    slug: "mr-ramesh-residence",
    title: "Mr. Ramesh Residence",
    formalTitle: "Mr. RAMESH RESIDENCE",
    category: "Residential Architecture",
    filterType: "Residential",
    subtitle: "A four-story luxury apartment and duplex penthouse.",
    image: "/images/interiors/ramesh_int.png",
    gallery: [
      "/images/ramesh/3 (1).jpg",
      "/images/ramesh/1 (1).jpg",
      "/images/ramesh/5 (2).jpg",
      "/images/ramesh/balcony.jpg",
      "/images/ramesh/living1.jpg",
    ],
    location: "SALEM",
    year: "2020 - 2022",
    area: "16,155 SQFT",
    scopeOfWork: "ARCHITECTURE, INTERIOR, STRUCTURAL DESIGN, LANDSCAPE",
    overview: "Mr. Ramesh Residence is a four-story apartment building that culminates in a luxurious duplex penthouse. The architectural language is defined by clean lines and a sophisticated material palette, offering a premium urban living experience while maintaining privacy and comfort for the residents.",
    designTypes: ["Architectural", "Interior", "Structural"],
  },
  {
    id: 3,
    slug: "kmch-diagnostic-center",
    title: "KMCH Diagnostic Center",
    formalTitle: "KMCH COMPREHENSIVE CANCER CENTER",
    category: "Health Care",
    filterType: "Healthcare",
    subtitle: "A landmark in patient-centric architectural wellness.",
    image: "/images/interiors/kmch_int.png",
    gallery: [
      "/images/kmch/1.jpg",
      "/images/kmch/2.jpg",
      "/images/kmch/3.jpg",
      "/images/kmch/6.jpg",
      "/images/kmch/8.jpg",
    ],
    location: "COIMBATORE",
    year: "2024",
    area: "18,000 SQFT",
    scopeOfWork: "ARCHITECTURE, INTERIOR, STRUCTURAL DESIGN",
    overview: "Kovai Medical Center & Hospital (KMCH) represents a landmark in patient-centric architectural wellness. The Comprehensive Cancer Center was designed to provide a healing environment through the use of natural light, soothing colors, and intuitive navigation, ensuring that medical technicality exists in harmony with patient comfort.",
    designTypes: ["Healthcare", "Architectural", "Structural"],
  },
  {
    id: 4,
    slug: "siva-trade-centre",
    title: "Siva Trade Centre",
    formalTitle: "SIVA TRADE CENTER",
    category: "Commercial Architecture",
    filterType: "Commercial",
    subtitle: "A dynamic commercial hub where form follows function.",
    image: "/images/interiors/siva_int.png",
    gallery: [
      "/images/sivatrade EXT/1 view 1.jpg",
      "/images/sivatrade EXT/2 view.jpg",
      "/images/sivatrade inter/1 lobby 1.jpg",
      "/images/sivatrade inter/11 ff double ht 1.jpg",
      "/images/sivatrade inter/17 conference 1.jpg",
    ],
    location: "TIRUPUR",
    year: "2021 - 2022",
    area: "25,394 SQFT",
    scopeOfWork: "ARCHITECTURE, INTERIOR, STRUCTURAL DESIGN",
    overview: "Siva Traders, a well-known enterprise in Tirupur, required a dynamic commercial hub. The resulting Siva Trade Centre is a multi-functional space where form follows function, featuring retail bays, executive offices, and logistics facilities within a cohesive and modern architectural envelope.",
    designTypes: ["Commercial", "Architectural", "Interior"],
  },
  {
    id: 5,
    slug: "drg-commercial-complex",
    title: "D.R.G Commercial Complex",
    formalTitle: "D.R.G INTEGRATED COMPLEX",
    category: "Commercial Architecture",
    filterType: "Commercial",
    subtitle: "Visibility-centric retail and premium office development.",
    image: "/images/interiors/drg_int.png",
    gallery: [
      "/images/DRG/1.jpg",
      "/images/DRG/1_8 - Photo.jpg",
      "/images/DRG/2_20 - Photo.jpg",
      "/images/DRG/3_30 - Photo.jpg",
      "/images/DRG/1_5 - Photo.jpg",
    ],
    location: "NAMAKKAL",
    year: "2021",
    area: "12,000 SQFT",
    scopeOfWork: "ARCHITECTURE, STRUCTURAL DESIGN",
    overview: "The D.R.G Complex is an integrated commercial development designed for maximum visibility. Situated in a prominent location in Namakkal, it features a mix of high-street retail spaces and premium offices, utilizing a bold facade to attract attention while providing high-quality internal environments.",
    designTypes: ["Architectural", "Structural"],
  },
  {
    id: 6,
    slug: "azure-penthouse",
    title: "Azure Penthouse",
    formalTitle: "THE AZURE PENTHOUSE",
    category: "Interior Design",
    filterType: "Interior",
    subtitle: "A serene urban sanctuary of minimalist luxury.",
    image: "/images/projects/azure-penthouse/hero.png",
    gallery: [
      "/images/ramesh/2 (2).jpg",
      "/images/ramesh/4 (2).jpg",
      "/images/ramesh/6 (2).jpg",
      "/images/ramesh/home-theater.jpg",
      "/images/ramesh/living.jpg",
    ],
    location: "COIMBATORE",
    year: "2024",
    area: "2,200 SQFT",
    scopeOfWork: "INTERIOR DESIGN, STYLING",
    overview: "The Azure Penthouse is an exercise in minimalist luxury. This urban sanctuary features a palette of cool tones and natural materials, creating a serene atmosphere high above the city. Every detail, from the custom furniture to the curated art pieces, has been chosen to enhance the sense of space and light.",
    designTypes: ["Interior Design", "Styling"],
  },
  {
    id: 7,
    slug: "the-apex-residences",
    title: "The Apex Residences",
    formalTitle: "THE APEX VERTICAL ECOLOGY",
    category: "Apartment Architecture",
    filterType: "Apartment",
    subtitle: "High-end urban living with integrated vertical greenery.",
    image: "/images/projects/apex-residences/hero.png",
    gallery: [
      "/images/jagan/11.jpg",
      "/images/jagan/13.jpg",
      "/images/jagan/58.jpg",
      "/images/jagan/66.jpg",
      "/images/jagan/68.jpg",
    ],
    location: "POLLACHI",
    year: "2024",
    area: "65,000 SQFT",
    scopeOfWork: "ARCHITECTURE, STRUCTURAL DESIGN, SUSTAINABILITY",
    overview: "The Apex Residences redefines vertical living in Pollachi through the integration of vertical greenery and sustainable design principles. This high-end apartment complex offers residents private gardens and shared natural spaces, creating a micro-climate that reduces energy consumption and improves well-being.",
    designTypes: ["Architectural", "Structural", "Sustainability"],
  },
];